In [7]:
import numpy as np

In [9]:
%%html
<style>
    .blue {
        background-color: #b3d9ff;
    }
    .green {
        background-color: #2ECC40;
    }
    .yellow{
        background-color: #ffffcc;
    }
     .red{
        background-color: #ffd6cc;
    }
</style>

# Tipos de datos


* En Python **todo** es un objeto, por tanto también lo son todos los tipos de datos 
* Dos tipos generales de datos:
    * Escalares. Son objetos indivisibles (piensa en ellos como los átomos del lenguage)
        * int, float, complex, bool (True or False), None
    * Contenedores o también llamados _tipos estructurados_: tienen estructura interna, contienen un número arbitrario de enlaces a otros objetos
        * strings (str) Listas, tuplas, diccionarios, conjuntos

In [11]:
a = 3             # objeto de tipo entero
g = True          # objeto de tipo booleano
l = [1, 2, 3]     # lista en la que sus tres elementos son enteros
b = [[1,2], "hola", 'adios']  #lista en la que su primer elemento es una lista y el segundo y tercero una cadena de caracteres
c = (1, 2, 3)     # tupla de enteros
d = { 'name' : "Fulano", 'last_name' : 'Perez', 'edad' : 18} # Diccionario, pares de llave-valor

* A diferencia de C las variables de Python _**no** están fuertemente tipadas_. Los tipos se asignan de forma implícita y se comprueban en tiempo de ejecución.

* Se puede verifica el tipo, clase, de un objeto con las funciones `type()` y `isinstance()` 

In [13]:
print('tipo a:', type(a))      # Imprimimos el tipo del objeto a
print('tipo l:', type(l))      # Imprimemos el tipo del objeto l

print(isinstance(l, list))    # Preguntamos si el objeto l es una instancia de la clase list

if (type(l) is list):          # Condición lógica con el operador is
    print("Era de tipo lista")

tipo a: <class 'int'>
tipo l: <class 'list'>
True
Era de tipo lista


<div class="red">
    
**Importantísimo!!**. 

   * El concepto de variable en Python es radicalmente diferente al de C. En Python el asignar un valor a una variable debes entenderlo como **enlazar una variable a un objeto (binding)**. Por ejemplo, en la asignación
    
```python
    a = 3 
```
  el interprete de Python crea el objeto de _tipo escalar_ 3 y _enlaza_ la variable `a` con dicho objeto. 
    
   * Todo objeto tiene un **identificador**. El identificador es único para cada objeto.  Con la función `id(a)` podemos acceder al identificador del objeto *enlazado* por la variable *a*.
   * En Python los objetos tienen ciertas caracteristícas (**propiedades**). Por ejemplo, una propiedad de los objetos es la **mutabilidad**:
    
> Hay objetos que son **mutables** y otros que son no-mutables **o inmutables**. Los objetos mutables se pueden modificar, los no-mutables no se pueden modificar. Por ejemplo, los enteros son objetos no mutables mientras que las listas son objetos mutables.
>  
   Es importantísimo que entiendas porque hay variables para las que la función id devuelve el mismo id o por qué cuando *aparentemente se modifican* las variables, algunas veces cambian su `id` pero en otras no. Debes entender:
 >   * La diferencia entre el objeto en sí y el enlace al objeto (la variable). 
 >   * La diferencia entre *crear* un objeto, *modificar* un objeto mutable y *enlazar* un objeto. **Si tienes dificultades pregunta pero no podrás programar en Python sino lo entiendes**. [Pythontutor](https://pythontutor.com/) es una muy buena herramienta para aprender Python. Estudia la salida del programa siguiente y luego ejecuta con el interpréte paso a paso el siguente [codigo](https://pythontutor.com/visualize.html#code=int_a%20%3D%203%0Aint_b%20%3D%20int_a%0A%0Aprint%28int_a,%20int_b%29%0Aprint%28id%28int_a%29,%20id%28int_b%29%29%0A%0A%23%20Modify%20the%20int%0Aint_a%20%2B%3D%201%0Aprint%28int_a,%20int_b%29%0Aprint%28id%28int_a%29,%20id%28int_b%29%29%0A%0A%0Al_a%20%3D%20%5B1,%202,%203%5D%20%0Al_b%20%3D%20l_a%0Al_c%20%3D%20%5B1,%202,%203%5D%0Al_d%20%3D%20l_a%5B%3A%5D%0A%0Aprint%20%28l_a,%20l_b,%20l_c,%20l_d%29%0Aprint%28id%28l_a%29,%20id%28l_b%29,%20id%28l_c%29,%20id%28l_d%29%29%0A%0A%23%20modify%20the%20list%0Al_a%5B0%5D%20%3D%20%5B4,5,6%5D%0Al_a%5B1%5D%20%3D%20%7B'name'%3A'fulano',%20'edad'%3A3%7D%0Al_a%5B2%5D%20%3D%203%0Al_a.append%20%283.5%29%0Aprint%20%28l_a,%20l_b,%20l_c%29%0Aprint%28id%28l_a%29,%20id%28l_b%29,%20id%28l_c%29%29%0A%0A%23%20copy%3F%0Al_d%20%3D%20l_a%5B%3A%5D%0Aprint%28%20id%28l_a%5B1%5D%5B'edad'%5D%29%20%29%20%23%C2%BFque%20pasa%20con%20L_d%5B1%5D%3F%0A%0Al_a%5B1%5D%5B'name'%5D%20%3D%20'Eduardo'%20%20%20%20%23%20modifico%20el%20objeto%0Al_a%5B1%5D%20%3D%20%5B9,10%5D%20%20%0Al_a%5B3%5D%20%3D%20100.4%0A%0A%0A%23%20Objetos%20inmutables%0As_a%20%3D%20%22Hello%20world%22%20%0As_b%20%3D%20s_a%0As_c%20%3D%20%22Hello%20world%22%0Aprint%28id%28s_a%29,%20id%28s_b%29,%20id%28s_c%29%20%29%0A%0As_a%20%3D%203%0As_b%20%3D%203%0As_c%20%3D%203.5%0As_d%20%3D%203.5%0Aprint%28id%28s_a%29,%20id%28s_b%29,%20id%28s_c%29,%20id%28s_d%29%20%29%0A%0A%0Al_a%20%3D%20%5B%20%5B1,2,3%5D,%20%281,2,3%29,%20%22hola%20don%20pepito%22,%20%7B'name'%3A'fulano',%20'edad'%3A3%7D%20%5D%0Al_d%20%3D%20l_a%5B%3A%5D&cumulative=false&curInstr=35&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)
   
   * Otras propiedades  de los objetos es si son **indexables** o si son **iterables**.

     Por ejemplo, las listas son objetos indexables (puedo acceder mediante un índice a sus elementos) y también son iterables (puedo recorrer sus elementos uno a uno mediante un bucle). Sin embargo los diccionarios **no** son indexables pero **si** son iterables.
 
</div>

In [24]:
# Las listas de Python son objetos indexables e iterables

l = [10, 20, 30, 40, 50]                 # l es un objeto indexable
print('Primer elemento de l:', l[0])


for i in l:                             # l es un objeto iterable.       
    print(i)                            #   Itero sobre los valores de l con un bucle for 

Primer elemento de l: 10
10
20
30
40
50


<div class='yellow'>

**Ejercicio:**
     
En Python es mas sencillo que en C intercambiar valores de variables (*swap*). ¿Entiendes por qué? 
    
> **Solución:**    
</div>

In [27]:
a = 3          # Primero se crea el objeto de tipo entero 3 y después se enlaza 
               # la variable a con el objeto creado
b = [1, 2, 3]  # Creo un objeto de tipo lista y lo enlazo

print ('Objeto a:', a, 'Objeto b:', b)

a, b = b, a    # Swapp: Enlazo la variable a con el objeto enlazado por la variable b
               # y b con el objeto que enlazaba a
    
print ('Objeto a:', a, 'Objeto b:', b)

# Este código (estrategia de C) NO intercambia los valores enlazados por a y b ¿entinedes porqué?
a = 3
b = [1, 2, 3]
print ('Objeto a:', a, 'Objeto b:', b)

a = b
b = a
print ('Objeto a:', a, 'Objeto b:', b)

Objeto a: 3 Objeto b: [1, 2, 3]
Objeto a: [1, 2, 3] Objeto b: 3
Objeto a: 3 Objeto b: [1, 2, 3]
Objeto a: [1, 2, 3] Objeto b: [1, 2, 3]


<div class='red'>

* Los **objetos** y **operadores** se pueden combinar para formar **expresiones** las cuales se evaluan para formar un nuevo objeto de un determinado tipo con el **valor de la expresión**. Los operadores `==` y `!=` permiten verificar si dos expresiones se evaluan o no al mismo valor. 

**Importante!** 

* No confundir el operador `==` con el operador `is`. Este último se utiliza para verificar si dos variables enlazan al mismo objeto, es decir, si ambos objetos tienen el mismo identificador. Verifica el siguiente código con [pythontutor](https://pythontutor.com/render.html#code=print%28'2%20%2B%203%20%3D%3D%204%20%2B%201%3A',%202%2B3%20%3D%3D%204%2B1%29%0A%0Aa%20%3D%202%20%2B%203%0Ab%20%3D%204%20%2B%201%0A%0Aprint%28'a%20%3D%3D%20b%3A',%20a%20%3D%3D%20b%29%0Aprint%28'a%20is%20b%3A',%20a%20is%20b%29%0Aprint%28'%5Cn'%29%0A%0A%0Aa%20%3D%20%5B1,%202,%203%5D%20%20%20%23%20Remmeber%20a%20is%20a%20mutable%20object%0Ab%20%3D%20a%5B%3A%5D%20%20%20%20%20%20%20%20%23%20soft%20copy%20of%20a%0A%0Aprint%28'a%20%3D%3D%20b%3A',%20a%20%3D%3D%20b%29%0Aprint%28'a%20is%20b%3A',%20a%20is%20b%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)
    
</div>

In [26]:
print('2 + 3 == 4 + 1:', 2 + 3 == 4 + 1)

a = 2 + 3
b = 4 + 1
print('a == b:', a == b)
print('a is b:', a is b)
print('\n')

a = [1, 2, 3]   # Remmeber a 
b = a[:]        # soft copy of a

print('a == b:', a == b)
print('a is b:', a is b)

2 + 3 == 4 + 1: True
a == b: True
a is b: True


a == b: True
a is b: False


<div class="blue">

**Ejercicio:**
    
Cuidado con Python, a veces su comportamiento es un *poco truculento*!! Lee el [documento](https://stackabuse.com/guide-to-string-interning-in-python/) e interpreta el resultado del siguiente código **después** de estudiar la sección de Tipos estructurados en Python que viene mas adelante

</div>    

In [19]:
s1 = 'foaba'
s2 = 'foaba'
print(id(s1), id(s2))
print('s1 == s2',  s1 == s2)
print('s1 is s2', s1 is s2)
print('\n')

s1 = 'foaba is a string'
s2 = 'foaba is a string'
print(id(s1), id(s2))
print('s1 == s2', s1 == s2)
print('s1 is s2', s1 is s2)
print('\n')

import sys
s1 = sys.intern('foaba is a string')
s2 = sys.intern('foaba is a string')
print(id(s1), id(s2))
print('s1 == s2', s1 == s2)
print('s1 is s2', s1 is s2)


139791890564336 139791890564336
s1 == s2 True
s1 is s2 True


139792267680688 139792562559680
s1 == s2 True
s1 is s2 False


139791890550816 139791890550816
s1 == s2 True
s1 is s2 True


# Tipos estructurados en Python

Python tiene cinco tipos estructurados: cadenas (`strings`), tuplas (`tuples`), listas (`lists`), diccionarios (`dicts`) y conjuntos (`sets`)

## String (cadenas):

* Son secuencias ordenadas de caracteres delimitadas por comillas simples, comillas dobles o triples


In [9]:
a = 'esto es una cadena con el caracter 3'
b = """esto es otra cadena 
en dos lineas"""
c = "ESTO ES OTRA CADENA"
print(a)
print(b)

esto es una cadena con el caracter 3
esto es otra cadena 
en dos lineas


* Las cadenas de caracteres son **objetos indexables**. Por tanto sus elementos (caracteres) son accesibles mediante un índice. 

In [10]:
print(a[0])    # accede al primer caracter de la cadena
print(a[-1])   # accede al ultimo caracter de la cadena
print(a[3:7])  # accede a los caracteres desde el cuarto al octavo

e
3
o es


* Las cadenas son **objetos inmutables**. Una vez creado un objeto inmutable no se puede modificar. Además de las cadenas de caracteres, en python existen otros tipos primitivos que también son inmutables, por ejemplo, `int, float, tuple`también lo son.  El siguiente código lanza una excepción de la clase `TypeError` cuando se intenta modificar la cadena de caracteres

In [11]:
a[0] = 3  # Error (se lanza una excepción) al intentar modificar el primer caracter de la cadena

TypeError: 'str' object does not support item assignment

* Las cadenas son objetos **iterables**, i.e., sus elementos se pueden iterar en un bucle

In [12]:
a = "Hello World"

# Iterando sobre la cadena
# En cada paso de la iteración x toma el valor de un caracter de la cadena a 
for x in a:
    print(x)

H
e
l
l
o
 
W
o
r
l
d


In [37]:
# Iterando sobre la cadena. Con el argumento modifico el caracter
# salto de carro que añade la función print 
for x in a:
    print(x, end = '')

esto es una cadena con el caracter 3

### Operadores que _operan_ sobre cadenas de caracteres

|Operator |	Operation	| Description |
|-------- | ------------ | ----------- |
|Assignament|	s1 = s2 |	Link s2 to the object linked by s1. |
|Concatenation|	s1 + s2 |	Creates a new string concatenating two strings, s1 and s2. |
|Repetition |	s * n	| Makes n copies of string, s.|
|Indexing	| s [ i ] |	Indexing a string, returning element at index i. |
|Slicing |	s[ i : j : step] 	| Slicing a string from i to j with an optional step.|
|Membership |	x in s |	Returns True if the element, x is in the string, s. Otherwise False.|
||x not in s | 	Returns True if the element, x is not in the string, x. Otherwise False.|
|Comparison |	s1 == s2 | 	Returns True if string, s1 is the same as string, s2. Otherwise False.|
 || s1 != s2 | 	Returns True if string, s1 is not the same as string, s2. Otherwise False.|

* Algunos ejemplos de operadores que admiten las cadenas de caracteres

In [32]:
str1 = "esto "
str2 = "ps" 

strc = str1 + str2    # concatenación
print (strc)

esto ps


In [47]:
a, b = str2            # assignment with unpacking is allowed when the object is iterable
print(a, b)

p s


El código anterior es equivalente a:

In [ ]:
a = str2[0]
b = str2[1]
print(a, b)

Otros ejemplos de operadores sobre cadenas de caracteres:

In [49]:
str1 = 'a es el primer caracter del alfabeto'
str2 = 'b el segundo'
print(str1 > str2)   
print(str1 * 3)      # repetition 
print('es' in str1)  # membership

False
a es el primer caracter del alfabetoa es el primer caracter del alfabetoa es el primer caracter del alfabeto
True


* Se pueden acceder a *trozos* de una cadena

In [34]:
a = "Hello World"

print(a)
print(a[:4])   # accede a los cuatro primeros caracteres
print(a[1:4])
print(a[::2] ) # accede a los caracteres que ocupan las posiciones pares: 0, 2, 
print(a[::-1]) # accede a la cadena inversa ¿Entenderías por qué?  
print(a[-1])   # accde al último elemento
print(a[-3:])  # accede a los ultimos 3 elementos 

print()
print(a)       # Obviamente NO se ha modificado la cadena oriiginal 

Hello World
Hell
ell
HloWrd
dlroW olleH
d
rld

Hello World


### Algunos métodos para manejar cadenas de caracteres

* Para acceder a los métodos de cualquier objeto '`a` se puede utilizar el tabulador o la función `dir()` o  la cambinación `a.` + tab 

In [55]:
a = "cadena de caracteres con un 3"
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

* Algunos ejemplos de métodos de cadenas de caracteres

In [56]:
a.upper() # Devuelve una cadena con la versión en mayúsculas del objeto a

'CADENA DE CARACTERES CON UN 3'

In [59]:
# Como a es una referencia al objeto, también es válido invocar al método accediendo directamente al abjeto
"cadena de caracteres con un 3".upper()

'CADENA DE CARACTERES CON UN 3'

In [60]:
print(a.isdigit()) # Comprueba si todos los caracteres del objeto a son dígitos

False


In [61]:
a[-1].isdigit()   # Comprueba si el último elemento de la cadena a es un dígito

True

In [62]:
a[:4].isalpha()  # comprueba si los 4 primeros caracteres de la cadena son síbmlos del alfabeto

True

In [63]:
string = 'con'
a.find (string) # busca la cadena string en a devolviendo el primer índice donde empieza o -1 si no se ha encontrado

21

In [65]:
a = 'Hello World'
a.split (sep = 'o') # devuelve una lista de subcadenas separadas por el separador indicado

['Hell', ' W', 'rld']

In [ ]:
a.split()  # sino se le pasa argumento al método, se asume el blanco como separador

* El método `join` concatena las cadenas incluidas en una lista que se le pasa como parámetro. En la concatenación utiliza como separador la cadena `separator`.

In [66]:
separator = 'XXX'
separator.join(['esto', 'es', 'una', 'cadena'])

'estoXXXesXXXunaXXXcadena'

### Algo mas...

* Puedes utilizar el constructor `str()`para *convertir* un objeto en un string. El resultado dependerá de la implementación  del método `__str__`  que haga el objeto que deseas convertir. En el siguiente ejemplo vamos a convertir el entero 127 a un string y después comprobaremos cual es el tipo del *nuevo* objeto.

In [44]:
a = 127
b = 127
print(type(a))
print(id(a), id(b))


# a enlaza ahora con el nuevo objeto, esto es, con la cadena de caracteres 127.  
a = str(a)
print(type(a))
print(id(a), id(b))

<class 'int'>
8916840 8916840
<class 'str'>
133705139592624 8916840


Deberíamos haber sido mas rigurosos con nuestro lenguaje. En el código anterior **no** hemos convertido un entero en una cadena: **hemos creado un nuevo objeto de la clase cadena de caracteres a partir de un objeto entero**. En el siguiente ejemplo creamos una cadena a partir de una lista

In [71]:
l = [1, 2, 3]
print(type(l))
print(id(l))

a = str(l)
print(type(a))
print(id(a))

<class 'list'>
140215127298176
<class 'str'>
140215127307376


 <div class='red'>

¿Qué hace exactamente la función `str()`? Como hemos dicho, ejecuta el método mágico `__str__` del objeto a partir del cual queremos crear la cadena de caracteres. Por ejemplo la sentencia `a = str(l)` es equivalente a

</div>    

In [ ]:
# Enlazo b con el resultado de ejecutar el método __str__() de la lista l
b = l.__str__()
type(b)

## Listas

### Introducción


Secuencia mutable, ordenada e iterable de **enlaces a objetos** (los elementos) posiblemente de diferentes tipos. Por tanto:
* sus elementos son accesible mediante un índice.
* se pueden obtener *trozos* de una lista (**Cuidado!!** creas una nueva lista donde las posiciones enlazan a los mismos objetos de la lista original)
* se puede iterar para obtener sus elementos

In [53]:
l = ["Hello world", 1, 2, [3,4], 4, 5, 6]
print(l)      # imprimo la lista
print(l[0])   # imprimo el objeto enlazado por primer elemento de la lista
print(l[-1])  # imprimo el objeto enlazado por el ultimo elemento de la lista
print()

l2 = l[:4]  # Crea un nuevo objeto de tipo lista con cuatro enlaces. 
            #   Las posiciones de la nueva lista enlazan a los cuatro primeros objetos 
            #   enlazados por la lista l

print(l2)    
print(l[3][0])

['Hello world', 1, 2, [3, 4], 4, 5, 6]
Hello world
6

['Hello world', 1, 2, [3, 4]]
3


 * Las listas son objetos iterables (el objeto lista implementa el método mágico `__iter__`) y por tanto pueden iterarse en un bucle

In [56]:
for item in l:
    print(item)

Hello world
1
2
[3, 4]
4
5
6


* Las Listas se pueden concatenarse con el operador  `+`

In [ ]:
l = ["Hello world", 1, 2, [3,4]]
l3 = ["Bye"] 
l = l[:2] +  l3
l

* `l =[ ]` crea una lista vacía. Es equivalente a `l = list()`

* `len(obj)` devuelve el número de elementos en la lista `obj` . La función *len* cuando se invoca sobre un objeto *ejecuta* el método mágico `__len__` de dicho objeto. 
* El operador `*` aplicado a una lista concatena la lista consigo misma tantas veces como se indique en el coeficiente   

In [60]:
l = 3 * [1,2]     # crea una lista concatenando 3 veces la lista [1,2]
print(l)
print(len(l))

[1, 2, 1, 2, 1, 2]
6


* La función `list(a)` crea una lista a partir del objeto iterable a

In [62]:
a = "cadena"  # cadena
b = list(a)
print(b)

['c', 'a', 'd', 'e', 'n', 'a']


In [64]:
d = {'nombre':'Eduardo', 'edad':27}  # diccionario
b = list(d)                          # crea una lista con las llaves del diccionario
print(b)

['nombre', 'edad']


* Cuando `list()`no reciba ningún argumento creará una lista vacía 

In [66]:
l = list()
print(l)

[]


* Las listas se pueden *desempaquetar*

In [ ]:
x, y, z = ["Hello", 'World', [1,2,3]]
print(x, y, z)
print(type(x), type(y), type(z))

<div class='blue'>
    
* Las listas están implementadas en C como arrays dinámicos de punteros a void, por tanto:
    * Añadir o eliminar elementos del final de la lista es rápido $O^*(1)$, i.e., $O(1)$ en coste amortizado.
    * Añadir o eliminar elementos de otras posiciones de la lista no es eficiente, $O(n)$. Por tanto la lista es una estructura de datos eficiente para implementar pilas pero no para colas.
</div>

<div class='yellow'>

**Cuestión:**
    
El siguiente código calcula el tamaño en memoria (en Bytes) de diferentes objetos en Python. ¿Que concluiones extraes?

In [21]:
import sys

l_empty = []
print(sys.getsizeof(l_empty))

# Lista enlaza 4 obejetos de tipo cadena de caracteres
l_cadena = ['hola don pepeito', 'paso usted ya por casa?', 
            'por su casa ya pase', 'y vio usted a mi abuela?'] 
print(type(l_cadena[0]))
print(sys.getsizeof(l_cadena))

# Lista enlaza 4 obejetos de tipo entero
l_int = [1, 2, 3, 4]
print(sys.getsizeof(l_int))
print(type(l_int[0]))

# Lista enlaza 4 obejetos de tipo lista
l_l =[[1,2,3], [4,5,6], [7,8,9], [8, 9, 10, 11, 12]]
print(sys.getsizeof(l_l))
print(type(l_l[0]))

# Lista enlaza 4 obejetos de diferente tipo
l_l =[[1,2,3], [4,5,6], [7,8,9], [8, 9, 10, 11, 12]]
print(sys.getsizeof(l_l))
print(type(l_l[0]))

# Lista enlaza 8 objetos de tipo entero
l = [x for x in range(8)]       
print(sys.getsizeof(l))

print()
# Lista con 6 enlaces de objetos diferente tipo 
seq = range(1000000)
l_d = [1, 'h', 'hola don pepito', [1,2,3], {'nombre': 'eduardo', 'edad': 20}, seq]
for item in l_d:
    print(type(item), 'size:', sys.getsizeof(item))

56
<class 'str'>
88
88
<class 'int'>
88
<class 'list'>
88
<class 'list'>
120

<class 'int'> size: 28
<class 'str'> size: 50
<class 'str'> size: 64
<class 'list'> size: 88
<class 'dict'> size: 184
<class 'range'> size: 48


### Algunos métodos de las listas

|Método          |Decripción                               |Peor caso, $^*$ coste amortizado       |
|:--------------|:------------------------------------------ | -----:|
|L.append(e)   |añade el objeto e al final de la lista L | $O^*(1)$|
|L.pop()   |elimina y devuelve el último elemento de la lista L. Lanza una excepción si L está vacía | $O^*(1)$|
|L.pop(i)   |elimina y devuelve el elemento que ocupa la posición i de la lista L. Lanza una excepción si L está vacía | $O(n)$|
|L.count(e)    |retorna le número de veces que aprece el objeto `e` en la lista L | $O(n)$|
|L.insert(i, e)|añade el objeto e en la lista L en la posición i | $O(n)$|
|L.remove(e)|elimina la primera ocurrencia del objeto e en la lista L| $O(n)$|
|L.extend(L1)|añade los elementos de la lista L1 al final de la lista L | $O(k)$|
|L.sort()|ordena en orden escendente los elementos de la lista L | $O(n \log n)$|

**Ejemplo.**

Uso de algunos métodos de listas [pythontutor](https://pythontutor.com/visualize.html#code=%23%20Ejemplo%20de%20uso%20de%20metodos%0A%0Al%20%3D%20%5B10,%202,%203,%201%5D%0Aprint%28id%28l%29%29%0A%0Al.append%28'Hola%20don%20pepito'%29%0Aprint%28id%28l%29%29%0A%0Aa%20%3D%20l.pop%28%29%0A%0Al.sort%28%29%0A%0Al%20%3D%20%5B10,%202,%203,%201%5D%0Als%20%3D%20sorted%28l%29&cumulative=false&heapPrimitives=nevernest&mode=edit&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

In [1]:
# Ejemplo de uso de metodos de un objeto

l = [10, 2, 3, 1]
print(id(l))

l.append('Hola don pepito')   
print(id(l))

a = l.pop()
l.sort()

l = [10, 2, 3, 1]
ls = sorted(l)

140193598491712
140193598491712


<div class="yellow">

**Ejercicio:**
    
Ejecuta paso a paso el siguiente script en [pythontutor](https://pythontutor.com/render.html#code=l%20%3D%20%5B%5B1,%202,%203%5D%20,%2020,%2030%5D%0A%0Ap%20%3D%20l%5B0%5D%0Al%5B0%5D%5B0%5D%20%3D%20'pepe'%0A%0Ap%5B0%5D%20%3D%20'Eduardo'%0Ap%20%3D%20'Andres'&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) analizando su salida y haciendo especial hincapie en los objetos enlazados.

**Ejercicio:**
    
¿Cúal será la silda del siguiente código? [pythontutor](https://pythontutor.com/render.html#code=L1%20%3D%20%5B%5B%5D%5D*2%0AL2%20%3D%20%5B%5B%5D,%20%5B%5D%5D%0A%0Afor%20i%20in%20range%28len%28L1%29%29%3A%0A%20%20%20%20L1%5Bi%5D.append%28i%29%0A%20%20%20%20L2%5Bi%5D.append%28i%29%0A%0Aprint%28'L1%20%3D',%20L1,%20'but',%20'L2%20%3D',%20L2%29&cumulative=false&curInstr=10&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

 </div>

In [ ]:
L1 = [[]]*2
L2 = [[], []]

for i in range(len(L1)):
    L1[i].append(i)
    L2[i].append(i)

print('L1 =', L1, 'but', 'L2 =', L2)

### Copia de listas *(shallow copy y deep copy)*

<div class="yellow">

**Ejercicio:** 

Suponga que se desea implementar una función `remove_dup(List: L1, List: L2)` para eliminar todos los elemntos de la lista L1 que se hallen en la lsta L2. 

Explica porqué la siguiente implementación de la función `remove_dup()` es incorrecta y proporciona una implementación correcta. 
    
</div>

In [1]:
def remove_dup(L1, L2):
    '''Assumes that L1 and L2 are lists.
    Removes any element from L1 that also occurs in L2
    Atención: Implementación incorrecta'''
    
    for ele in L1:
        if ele in L2:
            L1.remove(ele)


# main program 
L = [1, 2, 3, 4]      
Ld = [1, 2, 5, 6]

remove_dup(L, Ld)
print(L)

[2, 3, 4]


**Solución:**

> Una posible solución (hay otras soluciones posibles):
> * Hacer una copia de la lista `L1` antes de entrar en el bucle y cada vez que tuviese que eliminar un elemento lo eliminase de la lista-copia y no de la original. Pero ¿Cómo hacer una copia de una lista?
>
> Debes distinguir entre lo que es una referencia a un objeto, una copia superficial (**shallow copy**) y una copia profunda (**deep copy**). Analiza el siguiente [pythontutor](https://pythontutor.com/render.html#code=%0AL1%20%3D%20%5B1,%202,%203,%204%5D%0AL_ref%20%3D%20L1%20%20%23%20esto%20no%20es%20una%20copia%20ya%20que%20L_ref%20enlaza%20con%20el%20mismo%20objeto%20que%20L1%0A%0AL_shallow%20%3D%20L1%5B%3A%5D%20%23%20copia%20shallow%20se%20copian%20los%20elementos%20pero%20no%20los%20enlaces%20de%20estos%0AL1%20%3D%20%5B%5B1,%202%5D,%203,%204%5D%0AL_shallow%20%3D%20L1%5B%3A%5D%0A%0A%0Aimport%20copy%0AL_deep%20%3D%20copy.deepcopy%28L1%29&cumulative=false&curInstr=7&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

In [ ]:
import copy   # importo el modulo de la librería estandard

def remove_dup(L1, L2):
    '''Assumes that L1 and L2 are lists.
    Removes any element from L1 that also occurs in L2
    No muy buena solución'''
    
    L_copy = copy.deepcopy(L1)
    for ele in L1:
        if ele in L2:
            L_copy.remove(ele)

    return L_copy 

# main program 
L = [1, 2, 3, 4]      
Ld = [1, 2, 5, 6]

L_filter = remove_dup(L, Ld)
print(L_filter)

> * Una solución mucho mejor (¿sabrías decir porqué?) sería crear una nueva lista vacía y si el elemento de L1 no estuviese en L2 añadirlo a la nueva lista 

In [77]:
def remove_dup(L1, L2):
    '''Assumes that L1 and L2 are lists.
    Removes any element from L1 that also occurs in L2
    Mejor solución'''
    
    L_ = []                      # Creo una lista vacía
    for ele in L1:               #   recorro uno a uno la lista L1
        if ele not in L2:
            L_.append(ele)

    return L_ 

# main program 
L = [1, 2, 3, 4]      
Ld = [1, 2, 5, 6]

L_filter = remove_dup(L, Ld)
print(L_filter)

[3, 4]


### _List comprenhesion_

* Es una manera concisa, y muy utilizada, de crear listas a partir de un objeto iterable.
Por ejemplo suponga que se desea crear una lista con los cuadrados de los diez primeros números naturales. Una posibilidad sería:

<div class=yellow>
    
**Ejemplo**

Crea una lista que almacene el cuadrado de los primeros diez números enteros.

In [1]:
l = list()             # se crea una lista vacía
s = range(10)
for n in s:    # se añaden los elementos a la lista 
    l.append(n**2)
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

El código anterior se podría haber realizado utilizando *list comprenhesion*

In [178]:
l = [n**2 for n in range(10)]  # range(n) crea una secuencia iterable con los n elementos: 0,1, ... (n-1)
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

* Muchas veces se utiliza **_comprenhesion_** junto con **_unpacking_**. 

Supón que tienes una lista cuyos elementos son tuplas y se desea crear otra lista cuyos elementos sean la suma de los elementos de las tuplas. Una forma de hacerlo sería:

In [25]:
l = [(1,2), (3,4), (5,6)]         # lista cuyos elementos son tuplas

lc = [x[0] + x[1] for x in l]   
print (lc)

[3, 7, 11]


Pero habitualmente verás el siguiente código que utiliza **unpacking** y **list comprenhsion**

In [26]:
l = [(1,2), (3,4), (5,6)]    # lista cuyos elementos son tuplas

lc = [x + y for x, y in l]     # Cada iteración devuelve una tupla de la lista. 
                             # La tupla se despaqueta asignando a x e y los valores de la tupla
print (lc)

[3, 7, 11]


* Es muy habitual utilizar *list comprenhesion con condiciones* o *list comprenhesion con condicionales* (no son los mismo debes apreciar las diferencias entre ambas). 

Por ejemplo, el siguiente código crea una lista con los cuadrados de los primeros 25 numeros naturales múltiplos de 3 

In [6]:
# list comprension with condition
l = [n**2 for n in range(25) if n % 3 == 0]
l

[0, 9, 36, 81, 144, 225, 324, 441, 576]

El código anterior con *list comprenhesion* es equivalente al siguiente. 

In [7]:
# Codigo equivalente que no utiliza list comprenhesion
l = list()             # se crea una lista vacía
secuencia = range(25)
for n in secuencia:    # se añaden a lista solamente aquellos elementos
    if n % 3 == 0:     # de la secuencia que satisfacen la condición
        l.append(n**2)
l

[0, 9, 36, 81, 144, 225, 324, 441, 576]

* Podemos utilizar combinaciones *if/else* en list comprenhesion

In [14]:
# list comprenhension with conditionals

l = ['par' if n % 2 == 0 else 'tres' if n == 3 else 'impar' for n in range(10)]
l

['par', 'impar', 'par', 'tres', 'par', 'impar', 'par', 'impar', 'par', 'impar']

In [ ]:
que obviamente es equivalente a:

In [8]:
# Equivalente code to list comprenhension with conditionals

l = list()
secuencia = range(10)
for n in secuencia:
    if n % 2 == 0:
        l.append('par')
    elif n == 3:
        l.append('tres')
    else:
        l.append('impar')
l

['par', 'impar', 'par', 'tres', 'par', 'impar', 'par', 'impar', 'par', 'impar']

### Introducción a iteradores: funciones _zip()_,  _enumerate()_ y _range()_ 
 #### Función _zip()_

La función `zip()` devuelve un objeto de tipo `zip`. Un objeto zip es un `iterador` de tuplas. Un iterador es un objeto que permite generar objetos uno a uno para, eventualmente, operar con ellos. Para que un objetos sea un iterador debe implementar el método `next()`.

* Los parámetros que se le pasen a la función `zip()` deben ser obejetos iterables:
    * Sino no se le pasasa ningún parámetro, `zip()` devuelve un iterador vacío
    * Si se le pasa un único prámetro, `zip()` devuelve un iterador de tuplas, donde cada tupla tendrá un único elemento.
    * Si le pasas como argumento varios objetos iterables (por ehjemplo dos listas o dos objetos de tipo range) `zip()` devuelve un iterador de tuplas donde cada tupla tiene un elemento proveniente de cada uno de los iterables pasados como argumentos.

In [98]:
l1 = ['C', 'Python', 'JavaScript'] 
l2 = [17, 30, 40]
l3 = ['first', 'second', 'third', 'four']

# Creamos el iterador con la función zip pasándole como argumento tres listas
z = zip(l1, l2, l3) 
print(z)

* Una vez creado el iterador, la función next nos permite iterar el iterador obteniendo uno a uno sus objetos.

In [99]:
print(next(z))
print(next(z))
print(next(z))

('C', 17, 'first')
('Python', 30, 'second')
('JavaScript', 40, 'third')


El objeto devueltos en cada iteración del iterador `z` es una tupla con los correspondientes elementos de los argumentos con las que se creo `z`, en este caso tres listas. La primera vez que iteramos obtenemos  una tupla formada por los tres _primeros_ elementos de las tres listas. La segunda vez con los tres _segundos_ y la tercera vez con tres _terceros_. 
Si volviésemos a iterar `z` obtendríamos una excepción de la clase `StopIteration` porqué el iterador no puede generar mas objetos. 

In [31]:
next(z)

StopIteration: 

* Nota como el iterador genera tantos objetos como elementos tenga el menor de los iterables que se han utilizado para crear el objeto zip. En este caso la longitud del menor de los iterables utilizados era tres. 

* Aunque en el ejemplo anterior utilizamos la función `next()` para iterar, habitualmente un iteardor se itera con un bucle `for`

In [100]:
l1 = ['C', 'Python', 'JavaScript'] 
l2 = (1972, 2000, 1995)
l3 = ['Bell Labs', 'Centrum Wiskunde & Informatica', 'Netscape', 'Microsoft']

for item in zip(l1, l2, l3):
    print(item)

('C', 1972, 'Bell Labs')
('Python', 2000, 'Centrum Wiskunde & Informatica')
('JavaScript', 1995, 'Netscape')


* Apartir de un iterador podemos obtener una lista de objetos con la función `list()`.

In [159]:
z = zip(l1, l2, l3)  # creamos el iterador
l = list(z)          # creamos una lista apartir del iterador
print(l)

[('C', 1972, 'Bell Labs'), ('Python', 2000, 'Centrum Wiskunde & Informatica'), ('JavaScript', 1995, 'Netscape')]


* Cuando en el ejemplo anterior se ejecuta la sentencia `list(z)`, la función list itera el iterador y los objetos creados se almacenan en una lista. Por tanto, **después de ejecutarse** `list(z)` el **iterador se habrá extinguido**. Si ahora invocásemos a `next(z)` se lanzaría una excepción `StopIteration`  

In [160]:
next(z)

StopIteration: 

* También podemos crear una lista a partir de un iterador utilizando **list comprenhesion**. 

    En el ejemplo siguiente creamos un objeto de tipo `zip` con las secuencias devueltas por  `range(4)` y `range(100, 104)`, iteramos el iterador con un bucle `for` utilizando **unpacking** y **list comprenhesion** para generar una lista con los objetos que hemos ido generando [pythontutor](https://pythontutor.com/visualize.html#code=sequence1%20%3D%20range%284%29%0Asequence2%20%3D%20range%28100,%20104%29%0A%0Az%20%3D%20zip%28sequence1,%20sequence2%29%0Aa%20%3D%20next%28z%29%0Ab%20%3D%20next%28z%29%0A%0A%0Al%20%3D%20%5Bx*y%20for%20x,y%20in%20zip%28range%284%29,%20range%28100,%20104%29%29%5D&cumulative=false&heapPrimitives=nevernest&mode=edit&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

In [102]:
l = [x*y for x, y in zip(range(4), range(100, 104))]
l

[0, 101, 204, 309]

In [154]:
grocery = ['bread', 'milk', 'butter']

seq = range(len(grocery))
enum = enumerate(grocery, 10)    # iterador
z = zip(grocery, seq)            # iterador


print('enum -> list:', l_enum)
l_enum = list(enum)             # recorre el iterador enum
print(l_enum)
print()

l_z = list(z)
print(l_z)
print()


l_range = list(seq)
print(l_range)

enum -> list: [(10, 'bread'), (11, 'milk'), (12, 'butter')]
[(10, 'bread'), (11, 'milk'), (12, 'butter')]

[('bread', 0), ('milk', 1), ('butter', 2)]

[0, 1, 2]


<div class=yellow>

**Cuestión:**

Aunque el siguiente código produce los mismos resultados que el anterior **nunca** deberías utilizarlo. Explica porqué.

```python
# No utilizar nunca
buff = list(zip(range(4), range(100, 104)))
l = [x*y for x,y in buff]  
# ni tampoco
l = [x*y for x,y in list(zip(range(4), range(100, 104)))]    
```

<div class="red">
 
**Importante:**
    
* Recuerda que cuando añadimos un objeto a una **lista**, por ejemplo con el método append de la lista,  se crea el objeto y, después, este se enlaza en la lista. La memoria total utilizada será, por tanto, la suma del tamaño de todos los objetos enlazados en la lista mas el tamaño en sí de la lista, esto es, la estructura que implementa los enlaces de la lista.
    * Al ser la lista un objeto **iterable** esta se puede recorrer con un bucle for. Cuando se itera una lista con un bucle se recorren todos los objetos _ya creados_ y enlazados en la lista.

* Un **iterador**, sin embargo, **no almacena** **todos** los objetos sino que los crea **_on fly_**, esto es, _bajo demanda_: **no** se crea el objeto hasta que no se itera el iterador. 

    Para iterar un iterador (y, por tanto,  crear un nuevo objeto) hay que invocar a la función `next()` pasándole como argumento el iterador. Cada vez que se ejecuta la función `next()` el iterador cambia su estado interno de forma que la siguiente llamada a next() creará un nuevo objeto. También se puede iterar reiteradamente un iterador mediante un bucle `for`.
    * Cuando un iterador se itera reiteradamente llegará un momento en que este se **extinga** o mejor dicho, **se consuma**. Una vez extinguido un iterador, **no** se podrán crear mas objetos. 
    Si se invoca a la función `next()` con un iterador extinguido se lanzará una excepción de tipo `StopIteration`. 
    * Ten cuidado!!. Hay funciones que iteran reiteradamente un iterador hasta consumirlo. Por ejemplo la función `list()` cuando se le pasa como argumento un iterador devuelve una lista con los objetos creados tras iterar el iterador.
    * Desde el punto de vista del coste en memoria trabajar con iteradores es muy eficiente.  
 
* No confundas un **iterador** con un **iterable**. Hay objetos que son iterables pero que no son iteradores. Por ejemplo **no son iteradores** las listas o las tuplas. Tampoco lo son secuencias creadas creadas con la función `range()`.

* Existen funciones que devuelven un iterador. Por ejemplo:
    * La función **zip()** crea un objeto de tipo **zip** a partir de uno o varios objetos iterables. Un zip es un tipo concreto de iterador. En cada iteración de un objeto zip, bien con en un bucle `for` o bien o cuando se invoca a la función `next()`, se crea una tupla.
    * La función **enumerate()** o la función **reversed()** también crean iteradores.
    * Muchas de las funciones que trabajan con ficheros devuelven un iterador
   
* Hay otras formas de crear un iterador. Por ejemplo:
    * La función `iter()` crea un un iterador apartir de cualquier objeto que sea iterable.
    * Implementando una **función generador**. Las funciones generadores las veremos mas adelante.
    * Un **Generador de expresión** también crea un iterador. No debes confundirlos con list comprenhesion aunque su sintaxis sea muy similar.

<div class=yellow>

**Cuestión:**

Ejecuta y aniliza detenidamente la salida del siguiente programa. ¿Qué conclusiones extraes sobre el tamaño de los diferentes objetos?

In [128]:
import sys                                 # importo el modulo

# Objeto de tipo entero
print(type(0))
print('size int:', sys.getsizeof(int()))   # size in Bytes
print()

# Objetos de tipo range 
num = 1000000
sequence = range(num)  
sequence2 = range(num, 2*num)
print(type(sequence))                     
print('size range:', sys.getsizeof(sequence))
print(f'valor: {sequence[0]}, size:{sys.getsizeof(sequence[0])}')  # un objeto de tipo range es indexable
print(len(sequence))                       # implementa el metodo __len__()
print()

# Objeto de tipo lista
l = [x for x in sequence]                  # list comprenhesion
print(type(l))
print('tamaño de la lista:', sys.getsizeof(l))
print()

# Objeto de tipo zip
z = zip(sequence, sequence2)                # Genero un zip con dos secuencias
print(type(z))    
print('tamaño de zip:', sys.getsizeof(z) ) 
item = next(z)                              # Los elementos del zip son tuplas
print(f'valor:{item}, size: {sys.getsizeof(item)}')


<class 'int'>
size int: 28

<class 'range'>
size range: 48
valor: 0, size:28
1000000

<class 'list'>
tamaño de la lista: 8448728

<class 'zip'>
tamaño de zip: 64
valor:(0, 1000000), size: 56


#### Función  _enumerate()_

* La función `enumerate()` recibe un objeto iterable y devuelve un objeto de tipo  enumeración. Una enumeración es un **iterador**. Cuando se itera una **enumeración**, o se invoca a la función `new()`, se obtiene una tupla cuyo primer elemento es un entero y como segundo un enlace al correspondiente objeto de la lista.  
Al ser la enumeración un iterador esta se extingue cuando se itera reiteradamente. [Pythontutor](https://pythontutor.com/render.html#code=grocery%20%3D%20%5B'bread',%20'milk',%20'butter'%5D%0A%0Aenum%20%3D%20enumerate%28grocery%29%20%20%20%20%23%20Al%20invocar%20al%20constructor%20pasandole%20un%20iterable%0Aprint%28type%28enum%29%29%20%20%20%20%20%20%20%20%20%20%20%20%23%20creo%20un%20objeto%20de%20tipo%20enumeraci%C3%B3n%20%0A%0Aitem%20%3D%20next%28enum%29%20%20%20%20%20%20%20%20%20%20%20%20%23%20Cada%20vez%20que%20se%20itera%20una%20enumeraci%C3%B3n%0Aprint%28item%29%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20se%20crea%20una%20tupla%0Aprint%28type%28item%29%29%20%20%20%20%20%20%20%20%20%0Aprint%28%29%0A%0Al%20%3D%20%5B%5B1,%202%5D,%20%5B3,%204%5D,%20%5B5,6%5D%5D%0Ae%20%3D%20enumerate%28l%29%0Afor%20item%20in%20enumerate%28l%29%3A%20%20%20%23%20looping%20the%20enumerate%0A%20%20%20%20print%28item%29&cumulative=false&curInstr=16&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

In [210]:
grocery = ['bread', 'milk', 'butter']

enum = enumerate(grocery)    # Al invocar al constructor pasandole un iterable
print(type(enum))            # crea un objeto de tipo enumeración 

item = next(enum)            # Cada vez que se itera una enumeración
print(item)                  # se crea una tupla
print(type(item))         
print()

l = [[1, 2], [3, 4], [5,6]]
e = enumerate(l)
for item in enumerate(l):   # looping the enumerate until
    print(item)             # extinguish the enumeration

<class 'enumerate'>
(0, 'bread')
<class 'tuple'>

(0, [1, 2])
(1, [3, 4])
(2, [5, 6])


* Como cualquier otro iterador se puede convertir una enumeración a una lista o una tupla utilizando los constructores apropiados.

In [137]:
l = list(enumerate(grocery))     # creating a list from enumerate
print(l)

t = tuple(enumerate(grocery))
print(t)

[(0, 'bread'), (1, 'milk'), (2, 'butter')]
((0, 'bread'), (1, 'milk'), (2, 'butter'))


* La función `enumerate()` se puede invocar con **dos argumentos**. En este caso el segundo argumento inicia la enumeración.

In [125]:
# changing the default counter
enum = enumerate(grocery, 10) #con dos parametros

print(list(enum))

[(10, 'bread'), (11, 'milk'), (12, 'butter')]


#### Función _range()_

<div class='red'>
    
**Cuidado!!!** 

* La función `range()` crea _on-fly_ una secuencia
* Un objeto de tipo **range** **no es** un iterador. Aunque también sus elementos se crean _on fly_, no se puede invocar a la función next() sobre un un objeto de tipo range y, por tanto, **no se extinguirá** tras iterarlo. Sin embargo un objeto de tipo range es indexable y se puede hallar el tamaño de la secuencia con la función `len()`. [REF](https://treyhunner.com/2018/02/python-range-is-not-an-iterator/)

In [209]:
import sys

seq1 = range(0, 1000000, 2)
seq2 = range(0, 10, 2)

print(type(seq1))

print('size range:', sys.getsizeof(seq1))   # on fly
print('size range:', sys.getsizeof(seq2))

for i in seq2:     # Como NO es un iterador NO se consume
    print(i)
    
for i in seq2:
    print(i)
    
# Si ejecutas next(seq1) se lanzará una excepción 

<class 'range'>
size range: 48
size range: 48
0
2
4
6
8
0
2
4
6
8


<div class='blue'>

#### ¿iterador o un Iterable?
 
* ¿Cómo podríamos saber si un objeto es un iterador o es iterable? Una posibilidad sería importar el módulo collections y preguntar si el objeto es una instancia de la clase `collections.abc.Iterator` o de la clase `collections.abc.Iterable`
* ¿Se te ocurre otra posibilidad?

In [206]:
import collections.abc as co

l = ['hola', 'don', 'pepito']             # Iterable pero no iterador
ra = range(len(l))                        # Iterable pero no iterador (on fly == lazy)
z = zip(l, r)                             # Iterador
e = enumerate(l)                          # Iterador
ge = (n**2 for n in range(3))             # Iterador (expression generator)
lc = [n**2 for n in range(3)]             # Lista por tanto iterable 
rev = reversed(l)

print('List:', isinstance(l, co.Iterable), isinstance(l, co.Iterator) ) 
print('range:', isinstance(ra, co.Iterable), isinstance(ra, co.Iterator) ) 
print('zip:', isinstance(z, co.Iterable), isinstance(z, co.Iterator) ) 
print('enumerate:', isinstance(e, co.Iterable), isinstance(e, co.Iterator) ) 
print('expression_generatos:', isinstance(ge, co.Iterable), isinstance(ge, co.Iterator) ) 
print('list_comprenhesion:', isinstance(lc, co.Iterable), isinstance(lc, co.Iterator) ) 
print('reversed_list:', isinstance(rev, co.Iterable), isinstance(rev, co.Iterator) ) 

# Puedes iterar un iterador con la funcion next()
next(rev)


List: True False
range: True False
zip: True True
enumerate: True True
expression_generatos: True True
list_comprenhesion: True False
reversed_list: True True


'pepito'

## Tuplas

* Las tuplas son muy similares a las listas. Al igual que estas son una secuencia indexable de enlaces a objetos posiblemente de diferente tipo. Sin embargo, a diferencia de las listas, en las tuplas una vez que se han establecido los enlaces, estos **no se pueden re-enlazar**. Por esta razón las tuplas son objetos no mutables.

In [98]:
t =  ([1,2,3], 4, "hello world")
t

([1, 2, 3], 4, 'hello world')

In [5]:
t[0] = 3      # no permitido, no se pueden re-enlazar los enlaces de una tupla

TypeError: 'tuple' object does not support item assignment

In [ ]:
t = ((1, 2), 3, 4)
t[0][0] = 100 
print(t)

* Podemos crear una tupla vacía, con un elemento, o con varios elementos

In [ ]:
t = ()            # t es una tupla vacía
t2 = tuple()      # t2 también es una tupla vacía
t3 = ("hola", 2)  # tupla con dos elementos


'''Para crear una tupla con uníco elemento, la coma es necesaria 
sino la expresión t4 = (3) sería un enlace a un entero ''' 
t4 = (2,)   # t4 es una tupla con un elemento.  
t4

<div class='red'>

**Importante:** 

Suponga la tupla `t = ([1,2,3], 4, "hello world")` ¿Sería posible modificar el primer elemento de la tupla? No podríamos. Como hemos visto una tupla es un objeto **no mutable**. Pero cuidado *modificar* debe entenderse como **_modificar los enlaces_** (es decir que las posiciones de las tuplas enlacen objetos diferentes a los iniciales). Si lo intentamos se lanzará una excepción del tipo `TypeError: 'tuple' object does not support item assignment'`.  Lo que sí podemos es modificar los elementos *enlazados* de la tupla que sean mutables. Por ejemplo podemos modificar el contenido de la lista, incluso extraer todos sus elementos [pythontutor](https://pythontutor.com/render.html#code=t%20%3D%20%20%28%5B1,2,3%5D,%204,%20%22hello%20world%22%29%0A%0At%5B0%5D%5B0%5D%20%3D%20%22Eduardo%22%20%23%20modifico%20un%20elemento%20de%20la%20lista%0A%0At%5B0%5D.pop%28%29%20%20%23%20elimino%20un%20elemento%20de%20la%20lista%0A%0At%5B0%5D.clear%28%29%20%23elimino%20todos%20los%20elementos%20de%20la%20lista&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

In [ ]:
t =  ([1,2,3], 4, "hello world")
t[0] = "Eduardo"

In [ ]:
t[0][0] = "Eduardo"  # modifico un elemento de la lista
print (t)

t[0].pop()           # elimino un elemento de la lista
print(t)

t[0].clear()         # elimino todos los elementos de la lista
print(t)

* Al igual que en las listas `for` se puede utilizar para iterar sobre los elementos de la tupla y `in` para verificar si un elemento se encuentra en una tupla

In [ ]:
for x in t:
    print(x)
    
print('hello world' in t)

* Las tuplas permiten asignación múltiple. Lo cual es muy útil para capturar el retorno de una función (en Python una función retorna una tupla)

In [ ]:
a, b = (3, 4)
print(a, b)

In [ ]:
 def inspecciona(a, b, c):
        return min(a,b,c), max(a, b, c)

minimo, maximo = inspecciona(7, 9, 2)
print(minimo, maximo)

## Diccionarios

* Crear y usar un diccionario es muy parecido a trabajar con una lista, excepto que ahora debe definir un **par de clave y valor**, `key:value`. Los elementos del diccionario son accedidos por claves **no** por índice (es decir, **los elementos de un diccionario no son indexables**)

In [10]:
empleado = {'nombre' : 'Eduardo', 'apellido' : 'Santos', 'edad' : 25}
empleado

{'nombre': 'Eduardo', 'apellido': 'Santos', 'edad': 25}

* La gran ventaja de esta estructura de datos es que los diccionarios pueden proporcionar rápidamente acceso a elementos de datos específicos utilizando la clave. 
Los diccionarios son la implementación Python de las tablas Hash. 

In [13]:
print(empleado['nombre'], empleado['apellido'], empleado['edad'])

Eduardo Santos 25


* Hay límites para los tipos de claves que se pueden utilizar. Las reglas especiales para crear una clave son:
    * La clave debe ser única. Cuando se ingresa una clave duplicada, la información que se encuentra en la segunda entrada (resto es, el *valor* asignado a la *clave*) reemplaza a la de la primera.
     * La clave puede ser cualquier objeto inmutable. Esta regla implica que se pueden usar cadenas, números o tuplas para la clave. Sin embargo, no puede usar una lista para una clave.

In [6]:
# claves duplicadas. Se modifica el valor de la clave 2
registro = { 1:"Primer registro", 2:"Segundo registro", 2:"Tercer registro"}
print (registro)

# Diferentes tipos de claves
registro = { 1:"Primer registro", "Segundo registro":2, (1,2):"Primer registro y" + " Segundo registro" }
print(registro[1])
print(registro["Segundo registro"])
print(registro[(1,2)])

{1: 'Primer registro', 2: 'Tercer registro'}
Primer registro
2
Primer registro y Segundo registro


* Se pueden añadir elementos al diccionario mediante el método `update`o directamente

In [14]:
empleado.update ( {'estado_civil': 'soltero'})    # añade elemento con update
print (empleado)

empleado['profesion'] = 'soldador'                # añade elemento directamente
print (empleado)

{'nombre': 'Eduardo', 'apellido': 'Santos', 'edad': 25, 'estado_civil': 'soltero'}
{'nombre': 'Eduardo', 'apellido': 'Santos', 'edad': 25, 'estado_civil': 'soltero', 'profesion': 'soldador'}


* Se puede crear un dccionario vacío

In [ ]:
d1 = {}      # crea un diccionario vacío
d2 = dict()  # crea un diccionario vacío
d2

* El constructor `dict()`devolverá un dict cuando reciba una tupla cuyos elementos sean pares llave-valor

In [17]:
t = (('cofee', 1.), ('sugar', 0.75))     # tupla con pares de elementos
price = dict(t)                          # crea un diccionario a partir de la tupla anterior
price

{'cofee': 1.0, 'sugar': 0.75}

* Podemos preguntar si una clave se encuentra en un diccionario

In [23]:
print('salt' in price) 
print('sugar' in price)

False
True


* Los diccionarios **son** objetos **iterables**

In [21]:
for item in price:
    print(f'El precio de {item} es {price[item]}')


El precio de cofee es 1.0
El precio de sugar es 0.75


* Los diccionarios **no son indexables**. Cuando se intenta acceder a los elementos de objeto_2 se lanza una excepción. Verifica atentamente las diferencias entre los programas 

In [ ]:
objeto_1 = {1:'lapiz', 2:'papel', 3:'tijera'}
for i in range(1, 4):
    print( objeto_1[i])     # Es correcto accedo por llave. En este caso las llaves son enteros.

# código incorrecto
objeto_2 = {'uno':'lapiz', 'dos':'papel', 'tres':'tijera'}
for i in range(1, 4):
    print(objeto_2[i])

<div class="yellow">

**Ejercicio**
    
¿Es correcto el siguiente código? Justifica tu respuesta.

</div>    

In [ ]:
d = { nombre:'Eduardo', apellido:'Serrano'}

### Algunos métodos de los diccionarios

In [24]:
empleado.keys()      # devuelve una lista no ordenada con las claves del diccionario empleado

dict_keys(['nombre', 'apellido', 'edad', 'estado_civil', 'profesion'])

In [25]:
empleado.values() # devuelve un objeto que muestra una lista con los valores del diccionario

dict_values(['Eduardo', 'Santos', 25, 'soltero', 'soldador'])

In [26]:
empleado.items()  #devuelve un objeto que muestra una lista de tuplas con pares clave-valor

dict_items([('nombre', 'Eduardo'), ('apellido', 'Santos'), ('edad', 25), ('estado_civil', 'soltero'), ('profesion', 'soldador')])

### _Dictionary comprenhesion_

* Al igual que en las listas también tengo **dictionarty comprenhesion**

<div class="yellow">

**Ejercicio**: 


Suponga que tiene un diccionario con los precios en dólares de diferentes productos. Se desea crear un nuevo diccionario con los precios en euros. 
 
> **Solución** 
>    
> Deberíamos crear un nuevo diccionario donde los *valores* de las *llaves* se han multiplicado por el factor de conversión de dolar a euro:
    
</div>    

>  * Solución **sin** dictionary comprenhesion. Podemos crear un nuevo diccionario copia del anterior y modificar sus valores con un bucle `for`

In [183]:
price_dollar = {'milk': 1.02, 'coffee': 2.5, 'bread': 2.5}      # item price in dollars
conversion = 0.99  # 1$ equivalent to 0.99€

price_euro = dict(price_dollar)                                 # new (soft) copy
conversion = 0.99                                               # 1$ equivalent to 0.99€            

for item, value in price_euro.items():
    price_euro[item] = value * conversion

print(price_euro)    

{'milk': 1.0098, 'coffee': 2.475, 'bread': 2.475}


> * Solución mas compacta **utilizando _dictionary comprenhesion_**

In [200]:
price_euro = {item: value * conversion for item, value in price_dollar.items()}
print(type(price_euro))
print (price_euro)

<class 'dict'>
{'milk': 1.0098, 'coffee': 2.475, 'bread': 2.475}


<div class="yellow">

**Ejercicio**

Convierte la lista `l = ["coffe", 1.01, "milk", 2, 3]` en un diccionario donde las claves son los elementos pares la lista y las claves los impares.

> **Solución:**    

In [185]:
l = ["coffe",1.01, "milk", 2,3 ]

#method 1, dictionary comprenhesion with iterable
d = {key:values for key, values in zip(l[::2], l[1::2])}
print(d)

#method 1b, A little worst
d = {l[i]: l[i+1] for i in range(0, len(l) - 1, 2) }
print(d)

# method 2, using the dictionary constructor and a iterable
d = dict(zip(l[::2], l[1::2]))
print (d)

{'coffe': 1.01, 'milk': 2}
{'coffe': 1.01, 'milk': 2}
{'coffe': 1.01, 'milk': 2}


# Conjuntos

* Los conjuntos son otro tipo de colección. Son similares a los noción de conjunto en matemáticas: colecciones no ordenadas de **elementos no repetidos**. Se denotan con llaves.
* Los conjuntos sobjetos **mutables** pero **no indexables** 

In [ ]:
s = set()        # crea un conjunto vacío
s = {1, 2, 3}    

* No todos los objetos pueden ser elementos de un conjunto. Para que un elemento pueda ser miembro de un conjunto debe ser **_hashable_**. Un objeto es _hashable_ si tiene:
    * Un método `__hash__` que devuelve un objeto de tipo `int`
    * Un método `__eq__` que se utiliza para comparar su igualdad con otros elementos.
* Los objetos inmutables como los enteros, floats, cadenas de caracteres son _haseables_  y las tuplas solo si enlazan objetos inmutables   

## Algunos métodos de conjuntos

|Método          |Decripción                               |Operador asociado       |
|:--------------|:------------------------------------------ | -----:|
|add() |Adds an element to the set
|update() | add multiple elements to a set by passing a collection of elements (e.g., a list)
|clear() |Removes all the elements from the set
|copy() | Returns a copy of the set
|difference() |Returns a set containing the difference between two or more sets | - |
|difference_update() | Removes the items in this set that are also included in another, specified set
|discard() | Remove the specified item. Does not raise an error if the element is not in the set.
|intersection() | Returns a set, that is the intersection of two or more sets| & |
|intersection_update() | Removes the items in this set that are not present in other, specified set(s)
|isdisjoint() |Returns whether two sets have a intersection or not
|issubset() | Returns whether another set contains this set or not |  <= |
|issuperset() | Returns whether this set contains another set or not | >= |
|union()| | \|  |
|pop() | Removes an element from the set. Raise an error if the element is not in the set.

In [32]:
baloncesto = {'real_madrid', 'barcelona', 'joventut', 'baskonia'}
futbol = {'real_madrid', 'barcelona', 'atlético', 'bilbao'}

futbol.add('tenerife')
baloncesto.update(['estudiantes', 'tenerife'])

print('tenerife' in baloncesto)             # pertenece al conjunto    
print('alcoyano' not in baloncesto)         # no pertenece al conjunto

catalanes = {'barcelona', 'joventut'}
new_set = baloncesto.union({'getafe'})      # crea el conjunto unión
print(new_set)
print(catalanes <= baloncesto)
print(catalanes.issubset(baloncesto))

True
{'tenerife', 'estudiantes', 'baskonia', 'joventut', 'real_madrid', 'barcelona', 'getafe'}
True
True


* Un uso habitual de los conjuntos es para remover los duplicados de una lista

In [59]:
l = [1, 2, 3, 4, 2, 4]
l_new = list(set(l))
l_new

[1, 2, 3, 4]

# Funciones


## Introducción

* En Python una función se define utilizando la palabra clave `def`.
* En Python las funciones o bien no devuelven nada, `None`, o bien devuelven **una única** tupla de valores.

In [16]:
def foo():
    '''No retorna nada'''
    print("Hello world")

def suma(x, y):
    '''Retorna una tupla con un unico elemento'''
    suma = x + y
    return suma

def suma_prod(x, y):
    '''Retorna una tupla con 2 elementos'''
    suma = x + y
    prod = x * y
    return x, y

# main program

foo()
x = suma(7, 5)
z = suma_prod(7, 5)

print(z, type(z))

x, y = suma_prod(8, 2)   # desempaqueto el retorno de la función
print(x, y)

Hello world
(7, 5) <class 'tuple'>
8 2


<div class="red">

* En Python las funciones también son **objetos de primera clase**. No confundir el *objeto* función con la variable que *enlaza* a una función tal y como se muestra en el  [siguiente ejemplo](https://pythontutor.com/visualize.html#code=def%20add%28%29%3A%0A%20%20%20%20c%20%3D%2010%0A%20%20%20%20print%28f'%20Esto%20esta%20c%20dentro%20de%20la%20funcion%20add%3A%20%7Bc%7D'%29%0A%20%20%20%20%0Adef%20add_2%28%29%3A%0A%20%20%20%20c%20%3D%2020%0A%20%20%20%20print%28f'%20Esto%20esta%20c%20dentro%20de%20add_2%3A%20%7Bc%7D'%29%0A%0Ac%20%3D%201%0Aadd%28%29%0Af%20%3D%20add%0Af%28%29%0A%0Aadd%20%3D%20add_2%0Aadd%28%29&cumulative=false&heapPrimitives=nevernest&mode=edit&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

## Argumentos de funciones

* Al pasar valores a una función, Python usa las llamadas por **referencia a los objetos**.

<div class="red">
    
 **¿Qué ocurre si le pasamos un objeto mutable a una función?:**
    
* Al pasarle una referencia al objeto, el objeto podría ser modificado dentro de la función con efectos fuera del ámbito de la función.
* Sin embargo, si el enlace al objeto es re-enlazado dentro de la función, el ámbito externo no se _enterará de nada_ y no se realizarán cambios fuera del ámbito de la función.
 

En el siguiente ejemplo la variable `l` solo existe en ámbito interno de la función, esto es, en el  _local frame_ de la función `fun1()`. Cuando se invoca a `fun1()` en el programa principal, se asigna a la variable `l`  la lista enlazada por la variable `a` del _global frame_.  Como `l` enlaza a un objeto mutable, este puede ser modificado _dentro_ de la función y su _efecto_ se observa fuera del ámbito de la función.  

En cambio en `fun2()` como la variable `l` se re-asigna dentro de la función, los cambios que se realizan después **no** tienen efecto en la variable `a` del *global frame*.
    
 Ejecuta este ejemplo en [Pythontutor](https://pythontutor.com/render.html#code=def%20fun1%28l%29%3A%0A%20%20%20%20l%5B0%5D%20%3D%20%22hola%20don%20pepito%22%0A%20%20%20%20print%28'Valor%20de%20la%20lista%20dentro%20de%20fun1%28%29%3A',%20l%29%0A%20%0Adef%20fun2%28l%29%3A%0A%20%20%20%20l%20%3D%20%5B'a',%20'b',%20'c'%5D%0A%20%20%20%20l%5B0%5D%20%3D%20%22hola%20don%20pepito%22%0A%20%20%20%20print%28'Valor%20de%20la%20lista%20dentro%20de%20fun2%28%29%3A',%20l%29%0A%20%20%20%20%0A%23%23%23%23%23%23%20main%20program%20%0Aa%20%3D%20%5B1,%202,%203%5D%0Aprint%28'Valor%20de%20la%20lista%20antes%20de%20ejecutar%20fun1%28%29%3A',%20a%29%0Afun1%28a%29%0Aprint%28'Valor%20de%20la%20lista%20despues%20de%20ejecutar%20fun1%28%29%3A',%20a%29%0A%0Aa%20%3D%20%5B1,%202,%203%5D%0Aprint%28'Valor%20de%20la%20lista%20antes%20de%20ejecutar%20fun2%28%29%3A',%20a%29%0Afun2%28a%29%0Aprint%28'Valor%20de%20la%20despues%20de%20ejecutar%20fun2%28%29%3A',%20a%29&cumulative=false&curInstr=19&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)  
 
</div>  

In [9]:
def fun1(l):
    l[0] = "hola don pepito"
    print('Valor de la lista dentro de fun1():', l)
 
def fun2(l):
    l = ['a', 'b', 'c']
    l[0] = "hola don pepito"
    print('Valor de la lista dentro de fun2():', l)
    
# main program 
a = [1, 2, 3]
print('Valor de la lista antes de ejecutar fun1():', a)

fun1(a)
print('Valor de la lista despues de ejecutar fun1():', a)

a = [1, 2, 3]
print('Valor de la lista antes de ejecutar fun2():', a)
fun2(a)
print('Valor de la despues de ejecutar fun2():', a)

Valor de la lista antes de ejecutar fun1(): [1, 2, 3]
Valor de la lista dentro de fun1(): ['hola don pepito', 2, 3]
Valor de la lista despues de ejecutar fun1(): ['hola don pepito', 2, 3]
Valor de la lista antes de ejecutar fun2(): [1, 2, 3]
Valor de la lista dentro de fun2(): ['hola don pepito', 'b', 'c']
Valor de la despues de ejecutar fun2(): [1, 2, 3]


* Cuando se **invoca** a una función los valores que se pasan a la función se enlazan a los parámetros bien de forma posicional o utilizando los nombres formales de los parámetros

In [4]:
def fun(nombre, apellido, asignatura, curso):
    print (f' El estudiante {nombre} {apellido} se halla matriculado en {asignatura} de {curso}' )
    

# enlace posicional    
fun('Eduardo', 'Lopez', 'AlgED', 2)  # nombre enlaza a 'Eduardo', apellido enlaza a 'Lopez', ....

# enlace utilizando los nombres formales de los parametros
fun(apellido = 'Lopez', nombre = 'Eduardo', curso = 2, asignatura = 'AlgED')

 El estudiante Eduardo Lopez se halla matriculado en AlgED de 2
 El estudiante Eduardo Lopez se halla matriculado en AlgED de 2


* En Python también se pueden **definir** los argumentos de la función con valores por defecto. 
    * Los argumentos posicionales deben preceder a los argumentos con valor. 
    * Si al invocar a la función se omite un argumento con valor por defecto, la función asignará al parámetro el valor por defecto.
    * Los valores por defecto se definen mediante `arg = value`

In [37]:
def fun_pos (nombre, apellido, asignatura, curso):
    ''' Funcion sin valores por defecto
    '''
    print (f' El estudiante {nombre} {apellido} esta matriculado en {asignatura} de {curso}' )

def fun_clave (nombre, apellido, asignatura = 'AlgEd', curso = 2):
    ''' Con argumentos posicionales y argumentos con valor por defecto (default argument)
    '''
    print (f' El estudiante {nombre} {apellido} esta matriculado en {asignatura} de {curso}' )

# Ejemplos de invocación de funciones
fun_pos ('Eduardo', 'Lopez', 'AlgED', 2) 
fun_clave ('Mengano', 'Serrano')
fun_clave ('Zutano', 'Mejias', curso = 4, asignatura = 'Neuro')

 El estudiante Eduardo Lopez esta matriculado en AlgED de 2
 El estudiante Mengano Serrano esta matriculado en AlgEd de 2
 El estudiante Zutano Mejias esta matriculado en Neuro de 4


<div class='red'>

**Importante:**
    
* Cuidado con los argumentos que tienen un valor por defecto cuando este sea un objeto mutable. Cuando se crea el objeto función en el *frame de los objetos*, se inicializan los argumentos por defecto. Si estos se modificasen cuando se invocase a la función, las modificaciones persisten entre llamadas sucesivas. 

 * En la función `fun_peligrosa()` El argumento `l` tiene como valor por defecto una lista vacía. En la llamada a `fun_peligrosa (5)` como no se le ha pasado una lista el elemento 5 se añade a la lista *por defecto* `l`. Si ahora volvemos a invocar a fun_peligrosa **sin** el argumento por defecto, e.g.,  `fun_peligrosa(10)` el valor 10 se añade a la lista *por defecto* cuyo primer elemento era el 5. 
 * Compara la implementación de `fun_peligrosa()` con la de `fun_correcta()` y **analiza** que ocurre cuando se utiliza un valor por defecto en [Pythontutor](https://pythontutor.com/visualize.html#code=def%20fun_peligrosa%20%28ele,%20l%20%3D%20%5B%5D%29%3A%0A%20%20%20%20l.append%20%28ele%29%0A%20%20%20%20print%28l%29%0A%20%20%20%20%0Adef%20fun_correcta%20%28ele,%20l%20%3D%20None%29%3A%0A%20%20%20%20if%20l%20%3D%3D%20None%3A%0A%20%20%20%20%20%20%20%20l%20%3D%20%5B%5D%0A%20%20%20%20l.append%20%28ele%29%0A%20%20%20%20print%20%28l%29%0A%0A%23-------%20Driver%20program%20%0A%0Afun_peligrosa%20%285,%20%5B1,2,3,4%5D%29%20%20%20%20%0Afun_peligrosa%20%285%29%0Afun_peligrosa%20%2810%29%0A%0Afun_peligrosa%20%283,%20l%20%3D%20%5B1,1%5D%29%0Afun_peligrosa%20%28100%29%0A%0Afun_correcta%20%285,%20%5B1,2,3,4%5D%29%0Afun_correcta%20%285%29%0Afun_correcta%20%2810%29&cumulative=false&curInstr=47&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

 </div>

In [37]:
def fun_peligrosa (ele, l = []):
    l.append (ele)
    print(l)
    
def fun_correcta (ele, l = None):
    if l == None:
        l = []
    l.append (ele)
    print (l)

#------- Driver program 

fun_peligrosa (5, [1,2,3,4])    
fun_peligrosa (5)
fun_peligrosa (10)

fun_peligrosa (3, l = [1,1])
fun_peligrosa (5)

fun_correcta (5)
fun_correcta (10)

[1, 2, 3, 4, 5]
[5]
[5, 10]
[1, 1, 3]
[5, 10, 5]
[5]
[10]


* Cuando **se invoca** a una función, los argumentos posicionales se empaquetan en una `tupla` los argumentos sin valores por defecto (args) mientras que los argumentos con valores por defecto se empaquetan en un `dict` (kwargs) con los nombres de las variables como claves y los valores por defecto como valores del diccionario. Por ejemplo, en la función `fun_clave()` que hemos visto en el apartado anterior, `args = (nombre, apellido)` y `kwargs = {'asignatura' : AlgED', 'curso' : 2}` [pythontutor](https://pythontutor.com/render.html#code=def%20fun_pos%28nombre,%20apellido,%20asignatura,%20curso%29%3A%0A%20%20%20%20'''%20Solo%20argumentos%20posicionales%0A%20%20%20%20'''%0A%20%20%20%20print%20%28f'%20El%20estudiante%20%7Bnombre%7D%20%7Bapellido%7D%20esta%20matriculado%20en%20%7Basignatura%7D%20de%20%7Bcurso%7D'%20%29%0A%0Adef%20fun_clave%28nombre,%20apellido,%20asignatura%20%3D%20'AlgEd',%20curso%20%3D%202%29%3A%0A%20%20%20%20'''%20Con%20argumentos%20posicionales%20y%20argumentos%20por%20clave%20%28default%20argument%29%0A%20%20%20%20'''%0A%20%20%20%20print%20%28f'%20El%20estudiante%20%7Bnombre%7D%20%7Bapellido%7D%20esta%20matriculado%20en%20%7Basignatura%7D%20de%20%7Bcurso%7D'%20%29%0A%0A%23%20Driver%20program%0Afun_pos%28'Eduardo',%20'Lopez',%20'AlgED',%202%29%20%0Afun_clave%28'Mengano',%20'Serrano'%29%0Afun_clave%28'Zutano',%20'Mejias',%20curso%20%3D%204,%20asignatura%20%3D%20'Optimizaci%C3%B3n'%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

## Notación lambda para funciones anónimas

* Cuando las funciones son de una sola linea, a veces se definen por medio de la la notación `lambda`. En el siguiente ejemplo ambas definiciones de la función `square()`son equivalentes.  

In [13]:
def square(x):
    return x**2

square = lambda x: x**2

square(2)

4

<div class='red'>

* Sin embargo no debes abusar del uso de funciones lambda. Su uso solo está aconsejado en PEP8 como argumento de funciones (ver en la siguiente sección) o en funciones que solo se emplean una vez  [REF](https://treyhunner.com/2018/09/stop-writing-lambda-expressions/)

## Funciones como argumento de funciones

* En Python una función es un objeto mas y, por tanto, se puedo pasar una función como argumento de otra función. 

**Ejemplo**

Supongamos que tenemos una función (o funciones como en este caso) que tiene un único parámetro de entrada. Por ejemplo, las siguientes funciones calculan la *potencia al cuadrado* y la *potencia a la tres* del valor que se pasa a la función.

In [39]:
def cubic (x):
    return x**3

def square (x):
    return x**2

#-------------
print(cubic(2))
print(square(2))

8
4


Queremos crear una función `apply(l, f)`con dos parámetros de entrada, uno de tipo lista, l,  y otro que sea una función,f. La función `apply()` debe retornar una lista cuyos elementos sean el resultado de aplicar f a cada uno de los elementos de la lista `l`.

In [40]:
def apply(l, f):
    return [f(i) for i in l]  # list comprenhesion

# Driver program
l =  [4, 9, 25, 36]
print (apply(l, square) )
print (apply(l, cubic))

[16, 81, 625, 1296]
[64, 729, 15625, 46656]


Nuestra función `apply()` es correcta, pero  ¿y si quisiésemos invocar a `apply()` con una función que requiere parámetros adicionales? Por ejemplo queremos *aplicar* la función `power()` o la función `oper()` a los elementos de una lista ¿Qúe puedo hacer?. 

In [44]:
def power(base, exp_):
    return base**exp_

def oper(coef, base, exp_):
    return coef*(base**exp_)

Tengo, al menos, las siguientes alternativas:

 * Invocar `apply()` pasándole como argumento una función en notación lambda (ver el apartado de funciones `lambda`) que, a su vez, invoca a la función que quiero *aplicar* a los elementos de la lista. A la función lambada le paso los paraémetros adecuados.

In [48]:
l =  [4, 9, 25, 100]
print(apply(l, lambda x: power(x, 1./2.)))
print(apply(l, lambda x, y = 2, z = 3: oper(x, y, z)))
print(apply(l, lambda x, y = 2, z = 2: oper(x, y, z)))

[2.0, 3.0, 5.0, 10.0]
[32, 72, 200, 800]
[16, 36, 100, 400]


   * Definir la función `apply()` como una función con _un número variable de parametros_. La función incluye un parámetro *tipo* `*arg` (ver apartado a continuación).
   
   *Nota: Informalmente diremos que el parámetro _arg_ recibira una lista desempaquetada*

In [57]:
def apply(lista, f, *args):
    return [f(x, *args) for x in lista]

# Driver program
l =  [4, 9, 25, 36]
print(apply(l, power, 1/2))
print(apply(l, square))
print(apply(l, oper, 2, 2))

[2.0, 3.0, 5.0, 6.0]
[16, 81, 625, 1296]
[16, 36, 100, 144]


## Variables globales y funciones [ref](https://www.programiz.com/python-programming/global-keyword)

* In Python, `global` keyword allows you to modify the variable outside of the current scope. It is used to create a global variable and make changes to the variable in a local context.

* Rules of global Keyword
   * When we define a variable outside of a function, it is global by default. You don't have to use global keyword.
   * When we create a variable inside a function, it is local by default.
   * We use global keyword to read and write a global variable inside a function.
   * Use of global keyword outside a function has no effect.

<div class='yellow'>

**Ejemplo**
    
Ejemplo de variable global [ejemplo_1](https://pythontutor.com/visualize.html#code=def%20fun_l%28%29%3A%0A%20%20%20%20print%28'El%20valor%20de%20la%20lista%20global',%20l%29%0A%20%20%20%20l%5B0%5D%20%3D%20100%0A%20%20%20%20%0Adef%20fun_local%28%29%3A%0A%20%20%20%20print%28'El%20valor%20de%20la%20lista%20global',%20l%29%0A%20%20%20%20l%20%3D%20%5B1,%202,%203%5D%0A%20%20%20%20l%5B0%5D%20%3D%20100%0A%20%20%20%20%0A%20%20%20%20%0Al%20%3D%20%5B1,%202,%203%5D%0A%0Afun_l%28%29%0Aprint%28'El%20valor%20de%20l',%20l%29%0A%0Afun_local%28%29%0Aprint%28'El%20valor%20de%20l',%20l%29%0A%0A%0Ac%20%3D%2010&cumulative=false&heapPrimitives=nevernest&mode=edit&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

In [20]:
def fun_l():
    print('El valor de la lista global', l)
    l[0] = 100
    
def fun_local():
    l = [1, 2, 3]
    l[0] = 100

# main program    
    
l = [1, 2, 3]

fun_l()
print('El valor de l', l)

fun_local()
print('El valor de l', l)

El valor de la lista global [1, 2, 3]
El valor de l [100, 2, 3]
El valor de l [100, 2, 3]


* Sin embargo la siguiente función es incorrecta. Cuando se ejecuta se lanza una excepción de la clase `UnboundLocalError` Es importante que entiendas el mensaje de error!! 

In [21]:
c = 1 # global variable

def add():
    c = c + 2 # increment by 2
    print("Inside add():", c)

add()
print(f'In main: {c}')

UnboundLocalError: cannot access local variable 'c' where it is not associated with a value

En el código anterior se debería haber definido c como una variable global

In [59]:
c = 1 # global variable

def add():
    global c
    c = c + 2 # increment by 2
    print("Inside add():", c)

add()
print(f'In main: {c}')

Inside add(): 3
In main: 3


* Variable en una **función anidada** [example](https://pythontutor.com/render.html#code=def%20outside%28%29%3A%0A%0A%20%20%20%20def%20inside_not%28%29%3A%0A%20%20%20%20%20%20%20%20y%5B0%5D%20%3D%20%5B100,%20200%5D%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20inside_with%28y%29%3A%0A%20%20%20%20%20%20%20%20y%5B1%5D%20%3D%20500%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20inside_ret%28%29%3A%0A%20%20%20%20%20%20%20%20y%20%3D%20%5B50,%2050,%2050%5D%0A%20%20%20%20%20%20%20%20return%20y%0A%20%20%20%20%0A%20%20%20%20y%20%3D%20%5B1,%202,%203%5D%0A%20%20%20%20print%28f%22Before%20calling%20inside_not%3A%20%7By%7D%22%29%0A%20%20%20%20inside_not%28%29%0A%20%20%20%20print%28f%22After%20calling%20inside_not%3A%20%7By%7D%22%29%0A%20%20%20%20inside_with%28y%29%0A%20%20%20%20print%28f%22After%20calling%20inside_with%3A%20%7By%7D%22%29%0A%20%20%20%20return%20inside_ret%28%29%0A%0A%23%20main%20%20%20%20%0A%0Ay%20%3D%20outside%28%29%0Aprint%28f%22y%20in%20main%3A%20%7By%7D%22%29&cumulative=false&curInstr=25&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

In [30]:
def outside():

    def inside_not():
        y[0] = [100, 200]
        
    def inside_with(y):
        y[1] = 500
        
    def inside_ret():
        y = [50, 50, 50]
        return y
    
    y = [1, 2, 3]
    print(f"Before calling inside_not: {y}")
    inside_not()
    print(f"After calling inside_not: {y}")
    inside_with(y)
    print(f"After calling inside_with: {y}")
    return inside_ret()

# main    

y = outside()
print(f"y in main: {y}")

Before calling inside_not: [1, 2, 3]
After calling inside_not: [[100, 200], 2, 3]
After calling inside_with: [[100, 200], 500, 3]
y in main: [50, 50, 50]


## Argumentos *args* y *kwargs*

### En la invocación de una función

* En el siguiente ejemplo la función `fun()` tiene tres argumentos.  Podemos invocarla pasándole la lista `args`en la que, previamente, hemos desempaquetado sus elementos con `*`  

In [17]:
def fun(x, y, oper):
    ''' Funcion de tres argumentos'''
    if oper == '+':
        return x+y
    else:
        return x*y
        
args = (1, 2, '*')

a = fun(1, 2, '*')
print(a)

args = (1, 2, '*')
b = fun(args[0], args[1], args[2])
print(b)

c = fun (*args)  # equivalente a ejecutar: fun(args[0], args[1], args[2])
print(c)

2
2
2


* La siguiente función tiene dos argumentos posicionales (`x`e `y`) y uno por defecto (`tipo`). Podemos invocara a la función con una tupla que desempaquetamos para asignar valor a los argumentos posicionales y un diccionario que, a su vez, desempaquetamos para asignar los argumentos con clave. 

In [ ]:
def fun (x, y, tipo = 'triangulo'):
    if tipo == 'triangulo':
        return x*y/2
    else:
        return x*y

args = (4,2)
kwargs = { 'tipo' : "rectangulo"}
fun(*args, **kwargs) # equivalente a ejecutar: fun (args[0], args[1], tipo="rectangulo")

* La función anterior también podemos invocarla usando únicamente un diccionario que desempaquetamos

In [ ]:
kwargs = {'y':2, 'x':4,  'tipo' : "rectangulo"}
fun(**kwargs) # equivalente a ejecutar: fun (args[0], args[1], "rectangulo")

o una única tupla

In [ ]:
kwargs = (4, 2, "rectangulo")
fun (*args)

### En la definición de la función

* Podemos definir una función con un número arbitrario de parámetros posicionales mediante el uso de `args`. En el ejemplo, la variable args se enlaza a una tupla tal y como puedes observar en  [pythontutor](https://pythontutor.com/render.html#code=def%20add_arg_var%20%28*args%29%3A%0A%20%20%20%20value%20%3D%200%0A%20%20%20%20for%20i%20in%20args%3A%0A%20%20%20%20%20%20%20%20value%20%2B%3D%20i%0A%20%20%20%20print%20%28value%29%0A%20%20%20%20%0A%0Aadd_arg_var%20%283,4,5%29%0Aadd_arg_var%20%283,4,5,6%29&cumulative=false&curInstr=15&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

In [ ]:
def add_arg_var (*args):
    value = 0
    for i in args:  #se itera la tupla args
        value += i
    print (value)
    

add_arg_var (3,4,5)
add_arg_var (3,4,5,6)

* Igualmente con `**kwargs` podemos definir una función con un número arbitrario de parámetros con clave. En el siguiente ejemplo cuando se invoca a la función se enlaza `kwargs` con el dict {'base'=2, 'altura'=4} tal y como puedes comprobar en [pythontutor](https://pythontutor.com/render.html#code=def%20fun%28**kwargs%29%3A%0A%20%20%20%20for%20key,%20values%20in%20kwargs.items%28%29%3A%0A%20%20%20%20%20%20%20%20print%20%28key,%20values%29%0A%0Afun%20%28base%3D2,%20altura%3D4%29&cumulative=false&curInstr=2&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) 

In [ ]:
def fun(**kwargs):
    for key, values in kwargs.items():
        print (key, values)

fun (base=2, altura=4)

<div class="yellow">

**Ejemplo** 

En este ejemplo se utiliza kwargs tanto en la definición de la función `operacion`como en la llamada. En el ejemplo la función `operacion` necesita pasar diferentes argumentos según se invoque a la función `potencia`o a `logaritmo`[pythontutor](https://pythontutor.com/render.html#code=import%20math%0A%0Adef%20potencia%20%28x,%20exponente%3D2%29%3A%0A%20%20%20%20return%20x**exponente%0A%20%20%20%20%0Adef%20logaritmo%20%28x,%20base%3D10%29%3A%0A%20%20%20%20return%20math.log%28x,%20base%29%0A%0Adef%20operacion%20%28x,%20f,%20**kwargs%29%3A%20%20%23%20en%20la%20definici%C3%B3n%20de%20la%20funci%C3%B3n%0A%20%20%20%20return%20f%28x,%20**kwargs%29%20%20%20%20%20%20%20%20%23%20en%20%0A%0A%20%20%20%20%0A%0Aprint%20%28%20operacion%20%2810,%20potencia,%20exponente%20%3D%203%29%20%29%0Aprint%20%28%20operacion%20%2810,%20logaritmo,%20base%20%3D%2010%29%20%29&cumulative=false&curInstr=12&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false). 

In [18]:
import math

def potencia(x, exponente = 2):
    return x**exponente
    
def logaritmo(x, base = 10):
    return math.log(x, base)

def square(x):
    return x**2

def operacion(x, f, **kwargs):  # en la definición de la función
    ''' Version 1'''
    return f(x, **kwargs)        # en la invocacion tiene que pasarse los argumentos desempaquetados

# Drive code
print(operacion (x=10, f=potencia, exponente = 3) )
print(operacion (x=10, f=logaritmo, base = 10) )
print(operacion (x=10, f=square) )


1000
1.0
100


* La función `operacion()` podríamos programarla de otra forma. En este caso `operacion()` tiene un argumento con clave `param` cuyo valor por defecto es una lista vacía. Cuando `operacion()` invoca a `f` desempaqueta la tupla `param`   

In [ ]:
def operacion(x, f, param = tuple()):
    ''' Version 2 de la función operacion '''
    return f(x, *param)


# Drive code
print(operacion(x=10, f=potencia, param=(3,) ) )
print(operacion(x=10, f=logaritmo, param=(2,) ) )
print(operacion(x=10, f=square) )


## Anotación de funciones

* Anotar tus funciones mejorará mucho la legibilidad de tu código. Mediante la anotación indicamos cual deben ser los tipos de los parámetros de entrada a la función y el tipo del retorno de la función. En la siguiente página se muestran varios ejemplos
[anotación funciones](https://towardsdatascience.com/12-beginner-concepts-about-type-hints-to-improve-your-python-code-90f1ba0ac49)

* Recuerda que para anotar una función debes importar los módulos apropiados
```python
from typing import List, Tuple
```

In [ ]:
def cuadrado_text (x: float) -> str:
    '''Mediante la anotación indicamos cual deben ser los tipos de los
    paramatros de entrada a la función y el tipo del retorno'''
    
    return f'El cuadrado de {x} es {x**2}'

#----- Driver programm

print(cuadrado_text(3))

# Módulos

* Son ficheros _*.py_ que contienen sentencias, definición de funciones, variables globales, etc

* La sentencia `import` enlaza un módulo con el ámbito donde ocurre el import

* Si el fichero *my_module.py* ha sido modificado después del `import`, tiene que ser recargado para actualizar los enlaces previos: `reload (mm)`. La función reload realiza una comprobación sintáctica

* Se accede a las funciones (o variables) del módulo mediante notación de objetos (.): mm.funcname ( ... )



In [ ]:
%%bash  

ls -lht 
cat premier.py

In [ ]:
import './stack/stack'            # importo el modulo test.py 

test.fun ('Eduardo')   # se invoca a la funcion fun() del modulo 

In [45]:
import 

stakarray.reload (test)

test.fun('Pepe')

SyntaxError: invalid syntax (2160405305.py, line 1)

* Algunos módulos útiles

|Módulo |	Operation	|
|-------- | ------------| 
| os, sys |  para tareas relacionadas con el sistema operativo |
| math | para operaciones matemáticas estándar|
| matplotlib | para dibujar gráficas (lo veremos más adelante) |
|numpy | para álgebra lineal (lo veremos más adelante) |
| scipy | para cálculo científico |
| pandas | para cálculo con tablas (lo veremos más adelante) |
| sklearn | para aprendizaje automático (lo veremos más adelante) |
|statsmodels | para estadística|

## Numpy
### Arrays


* Supongamos que deseamos hacer ciertos cálculos algebraicos y necesitamos utilizar vectores y matrices. ¿Como podemos implementarlas en Python?  Podemos utilizar listas  o mucho mejor con Arrays, objetos definidos en el módulo Numpy.

    En el siguiente [Tutorial básico](https://numpy.org/doc/stable/user/quickstart.html) tienes una muy introducción a los arrays de numpy. Consúltalo antes de realizar los siguientes ejemplos 

In [33]:
# Utilizando listas
v = [1, 2, 3] 
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
import numpy as np

a = np.array ([1, 2, 3])                                # crea un array unidimensional a partir de una lista
b = np.array ([[1, 2, 3], [14, 5, 6], [27, 8, 9]])      # crea un array bi-dimensional

print(a)
print(b)

[1 2 3]
[[ 1  2  3]
 [14  5  6]
 [27  8  9]]


In [64]:
print(np.shape(a))   # Return the shape (dimension) of the numpy object. Equivalent to variable: m.shape
print(np.shape(b))

(3,)
(3, 3)


* Los arrays se pueden indexar y acceder a un subconjunto de sus elementos

In [95]:
print(b[1, 1])
print(b[0, :])         # Primera fila
print(b[0, 1:3])       # Los elementos de la primera fila que pertenecen a la segunda y tercera columna 
print(b[:, 1])

5
[0 1 2 3]
[1 2]
[1 5 9]


* Dado un array se puede mostrar con otras dimensiones (cuidado la diferencia entre mostrar y modificar) 

In [8]:
c = np.arange(6)  # Equivalente a la funcion range() pero devuelve un array
print(c)
c.reshape(3,2)    #  Muestra con otro shape

[0 1 2 3 4 5]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
print(c)
c = c.reshape(3,2)    # Modifico
print('Tras el reshape:')
print(c)

[[0 1]
 [2 3]
 [4 5]]
Tras el reshape
[[0 1]
 [2 3]
 [4 5]]


In [97]:
c.reshape(2, -1) # Con -1 la segunda dimensión se ajusta para que sea compatible

array([[0, 1, 2],
       [3, 4, 5]])

**Métodos de array**

In [54]:
m = np.empty((3,3))     # Return a new array of given shape without initializing entries (3,3)
m = np.zeros((3, 3))    # una matriz cuadrada 3 x 3 llena de ceros
i = np.eye(3)           # matriz identidad de 3 x 3

a = np.array([[1,0,1], 
              [0,1,0], 
              [0,0,1]])
print(a + i)             # suma elemento a elemento
print(a * i)             # multiplicación elemento a elemento
print(a.dot(i))          # multiplication de dos arrays
print(a / 5)             # división elemento a elemento
l = np.array(a)          # conversión de lista en array
print(a.T)               # traspuesta
np.linalg.det(a)         # determinante

[[2. 0. 1.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.2 0.  0.2]
 [0.  0.2 0. ]
 [0.  0.  0.2]]
[[1 0 0]
 [0 1 0]
 [1 0 1]]


1.0

**Algunas funciones**

In [ ]:
a = np.random.randint (0, high=11, size= (4,4)) #Return random integers from low (inclusive) to high (exclusive).
print(a)

print( a.mean(axis=0) )     # media de las columnas de a
print( a.mean(axis=1) )
a.mean()                    # media de todos los elementos del array

* En numpy todas sus funciones están paralelizadas

<div class='red'>
  
**Cuidado**
    
* Debes tener en cuenta que la gestion de memoria de los arrays de numpy es diferente a la de las listas. A diferencia de una lista donde al acceder a una sub-secuencia de una lista _se crea una nueva lista que enlaza los objetos de la lista original_, si accedes a una porción de un array de numpy **no** se crea un nuevo array,  accedes a los datos almacenados en l arry original. 
    
    Analiza detenidamente el siguiente código 

In [80]:
import numpy as np

# Cuidado con las sub-secuencias. 
# Una subsecuencia crea una nueva lista 
# que enlaza a los mismos objetos que la lista anterior

l = [900, 800, 700, 600]
s_l = l[1:3]
print(type(l), type(s_l))

print(f'l:{l}, porcion:{s_l}')
s_l[1] = 0       
print(f'l:{l}, porcion:{s_l}')
  
# Y si fuesen numpy arrays?
a = np.array([900, 800, 700, 600])
s_a = a[1:3]
print(type(a), type(s_a))

print(f'l:{a}, copia:{s_a}')
s_a[1] = 0       
print(f'l:{a}, copia:{s_a}')

<class 'list'> <class 'list'>
l:[900, 800, 700, 600], porcion:[800, 700]
l:[900, 800, 700, 600], porcion:[800, 0]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
l:[900 800 700 600], copia:[800 700]
l:[900 800   0 600], copia:[800   0]


In [90]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
print(a.shape)

b = a    # a y b enlazan al mismo objeto
print(a is b, id(a) == id(b))

(3, 4)
True True


* Repasa en el [tutorial](https://numpy.org/doc/stable/user/quickstart.html)  los métodos view y copy de un array. Analiza el siguiente código 

In [94]:
c = a.view()           # crea un nuevo array que comparte (la p0rción de memoria de) los datos con a
print(c is a)    
print(c.base is a)
print(a.data)
print(c.data)

c = c.reshape((2, 6))
print(a.data)
print(c.data)
print(a)
print(c)

False
True
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
